application:
  # -- The exposed port of the application
  appPort: 8501
  # -- The image used for the initial chatbot application interface
  appContainer: "quay.io/redhat-ai-dev/chatbot:latest"

model:
  # -- The image used for the initContainer of the model service deployment
  initContainer: "quay.io/redhat-ai-dev/granite-7b-lab:latest"
  # -- The model service initContainer command
  modelInitCommand: "['/usr/bin/install', '/model/model.file', '/shared/']"
  # -- The path of the model file inside the model service container
  modelPath: "/model/model.file"
  # -- The image used for the model service
  modelServiceContainer: "quay.io/ai-lab/llamacpp_python:latest"
  # -- The exposed port of the model service
  modelServicePort: 8001

gitops:
  # -- The name of the Secret containing the required Github token
  gitSecretName: "github-secrets"
  # -- The name of the Secret's key with the Github token value
  gitSecretKeyToken: "GITHUB_TOKEN"
  # -- The Github Repository with the contents of the ai-lab sample chatbot application
  gitSourceRepo: "redhat-ai-dev/ai-lab-samples"
  # -- The default branch for the chatbot application Github repository
  gitDefaultBranch: "main"
  # -- [REQUIRED] The Github Organization name that the chatbot application repository will be created in
  githubOrgName: ""
  # -- [REQUIRED] The quay.io account that the application image will be pushed
  quayAccountName: ""
