name: Lint Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  check-readme:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # pin@v4
        with:
          python-version: 3.12

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # pin@v3
        with:
          go-version: ^1

      - name: Setup helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # pin@v3.0.1
        with:
          extra_args: helm-docs --all-files

  check-jsonschema-dereference:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # pin@v4
        with:
          python-version: 3.12

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # pin@v3
        with:
          go-version: ^1

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
        with:
            extra_args: jsonschema-dereference --all-files
